#!/usr/bin/env node

import { writeFile, access } from 'fs/promises'
import { createInterface } from 'readline'
import { exec } from 'child_process'
import { promisify } from 'util'

const execAsync = promisify(exec)

const readline = createInterface({
  input: process.stdin,
  output: process.stdout,
})

const question = (query) => new Promise((resolve) => readline.question(query, resolve))

const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  red: '\x1b[31m',
}

function log(message, color = colors.reset) {
  console.log(`${color}${message}${colors.reset}`)
}

async function fileExists(path) {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

async function openBrowser(url) {
  const platform = process.platform
  const command =
    platform === 'darwin' ? 'open' : platform === 'win32' ? 'start' : 'xdg-open'

  try {
    await execAsync(`${command} ${url}`)
    return true
  } catch {
    return false
  }
}

async function verifySupabaseConnection(url, anonKey) {
  try {
    const response = await fetch(`${url}/rest/v1/`, {
      headers: {
        apikey: anonKey,
        Authorization: `Bearer ${anonKey}`,
      },
    })
    return response.ok
  } catch {
    return false
  }
}

async function main() {
  console.clear()
  log('\n🚀 Welcome to My Stack Template Setup!\n', colors.bright + colors.blue)

  // Check if .env.local already exists
  const envExists = await fileExists('.env.local')
  if (envExists) {
    log('⚠️  .env.local already exists!', colors.yellow)
    const overwrite = await question(
      'Do you want to overwrite it? (y/N): '
    )
    if (overwrite.toLowerCase() !== 'y') {
      log('\n✅ Setup cancelled. Your existing .env.local was not modified.\n', colors.green)
      readline.close()
      return
    }
  }

  log('This script will help you configure your Supabase project.\n')

  // Ask if they have a Supabase project
  const hasProject = await question('Do you already have a Supabase project? (y/N): ')

  if (hasProject.toLowerCase() !== 'y') {
    log('\n📝 Let\'s create a Supabase project first!\n', colors.blue)
    log('Opening Supabase dashboard in your browser...\n')
    
    const opened = await openBrowser('https://supabase.com/dashboard/projects')
    if (!opened) {
      log('Could not open browser automatically.', colors.yellow)
      log('Please visit: https://supabase.com/dashboard/projects\n')
    }

    log('Steps to create a project:')
    log('  1. Sign in or create a Supabase account')
    log('  2. Click "New Project"')
    log('  3. Choose a name and database password')
    log('  4. Wait for the project to be created (~2 minutes)')
    log('  5. Go to Settings → API\n')

    await question('Press Enter when your project is ready...')
  }

  log('\n🔑 Now let\'s get your Supabase credentials.\n', colors.blue)
  log('You can find these in your Supabase Dashboard:')
  log('  → Settings → API\n')

  // Get Supabase URL
  let supabaseUrl = ''
  while (!supabaseUrl) {
    supabaseUrl = await question('Enter your Supabase Project URL: ')
    supabaseUrl = supabaseUrl.trim()
    
    if (!supabaseUrl) {
      log('❌ URL cannot be empty!\n', colors.red)
    } else if (!supabaseUrl.startsWith('https://') || !supabaseUrl.includes('supabase.co')) {
      log('❌ URL should look like: https://xxxxx.supabase.co\n', colors.red)
      supabaseUrl = ''
    }
  }

  // Get Supabase Anon Key
  let supabaseAnonKey = ''
  while (!supabaseAnonKey) {
    supabaseAnonKey = await question('Enter your Supabase Anon Key: ')
    supabaseAnonKey = supabaseAnonKey.trim()
    
    if (!supabaseAnonKey) {
      log('❌ Anon Key cannot be empty!\n', colors.red)
    }
  }

  // Verify connection
  log('\n🔍 Verifying connection...', colors.blue)
  const isValid = await verifySupabaseConnection(supabaseUrl, supabaseAnonKey)

  if (!isValid) {
    log('⚠️  Could not verify connection to Supabase.', colors.yellow)
    log('This might be okay if your project is still initializing.')
    const proceed = await question('Continue anyway? (y/N): ')
    
    if (proceed.toLowerCase() !== 'y') {
      log('\n❌ Setup cancelled.\n', colors.red)
      readline.close()
      return
    }
  } else {
    log('✅ Connection verified!', colors.green)
  }

  // Create .env.local file
  const envContent = `# Supabase Configuration
# Generated by setup script on ${new Date().toISOString()}

NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnonKey}

# Optional: Add your service role key if needed for admin operations
# SUPABASE_SERVICE_ROLE_KEY=
`

  try {
    await writeFile('.env.local', envContent)
    log('\n✅ .env.local file created successfully!', colors.green)
  } catch (error) {
    log('\n❌ Error creating .env.local file:', colors.red)
    log(error.message, colors.red)
    readline.close()
    return
  }

  // Next steps
  log('\n🎉 Setup complete!', colors.bright + colors.green)
  log('\n📋 Next steps:', colors.blue)
  log('  1. Run: npm run dev')
  log('  2. Open: http://localhost:3000')
  log('  3. Try signing up for an account\n')
  log('💡 Tip: Check the README.md for more information.\n')

  readline.close()
}

main().catch((error) => {
  log('\n❌ An error occurred:', colors.red)
  log(error.message, colors.red)
  readline.close()
  process.exit(1)
})
